#!/usr/bin/env bash

# tum 全自动配置脚本 (V0.3 整合版)

while true; do
    CHOICE=$(whiptail --title "tum" --menu "请选择操作：" 15 60 5 \
        "1" "一键安装基础环境 (Git, Zsh, Curl等)" \
            "2" "一键配置终端美化 (Zsh + Oh My Zsh)" \
                "3" "一键安装 Ubuntu 系统 (V0.3)" \
                    "4" "退出" 3>&1 1>&2 2>&3)

                        if [ -z "$CHOICE" ]; then
                                break
                                    fi

                                        case $CHOICE in
                                                1)
                                                            clear
                                                                        echo "=== 正在更新软件源 ==="
                                                                                    pkg update -y && pkg upgrade -y

                                                                                                            echo "=== 正在安装基础环境 ==="
                                                                                                                        pkg install -y git curl wget zsh micro

                                                                                                                                                echo "✅ 基础环境安装完成！按回车返回主菜单..."
                                                                                                                                                            read -r
                                                                                                                                                                        ;;
                                                                                                                                                                                2)
                                                                                                                                                                                            clear
                                                                                                                                                                                                        echo "=== 正在配置终端美化 (Zsh + Oh My Zsh) ==="

                                                                                                                                                                                                                                # 1. 安装 Zsh
                                                                                                                                                                                                                                            if ! command -v zsh &> /dev/null; then
                                                                                                                                                                                                                                                            echo "正在安装 Zsh..."
                                                                                                                                                                                                                                                                            pkg install -y zsh
                                                                                                                                                                                                                                                                                        fi

                                                                                                                                                                                                                                                                                                                # 2. 安装 Oh My Zsh
                                                                                                                                                                                                                                                                                                                            if [ ! -d "$HOME/.oh-my-zsh" ]; then
                                                                                                                                                                                                                                                                                                                                            echo "正在克隆 Oh My Zsh..."
                                                                                                                                                                                                                                                                                                                                                            git clone https://gitee.com/mirrors/oh-my-zsh.git ~/.oh-my-zsh
                                                                                                                                                                                                                                                                                                                                                                            cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
                                                                                                                                                                                                                                                                                                                                                                                        fi

                                                                                                                                                                                                                                                                                                                                                                                                                # 3. 安装增强插件
                                                                                                                                                                                                                                                                                                                                                                                                                            echo "正在安装 Zsh 增强插件..."
                                                                                                                                                                                                                                                                                                                                                                                                                                        if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                        git clone https://gitee.com/mirrors/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                git clone https://gitee.com/mirrors/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fi

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 4. 修改配置文件 (动态获取当前用户名，彻底解决名字乱码)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "正在优化 Zsh 配置..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/' ~/.zshrc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "export DEFAULT_USER=\"$(whoami)\"" >> ~/.zshrc

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "✅ 终端美化配置完成！"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "请输入 zsh 体验新界面，或重启 Termux 自动进入。"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "按回车键返回主菜单..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                read -r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clear
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "=== 正在准备安装 Ubuntu 系统 (V0.3) ==="

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 1. 安装 proot-distro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if ! command -v proot-distro &> /dev/null; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "正在安装 proot-distro..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pkg install -y proot-distro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fi

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 2. 检查并安装 Ubuntu
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if [ -d "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu" ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "✅ Ubuntu 已经安装过了！"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "正在下载并安装 Ubuntu (可能需要几分钟，请保持网络畅通)..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            proot-distro install ubuntu
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fi

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "✅ Ubuntu 环境准备就绪！"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "输入 proot-distro login ubuntu 即可进入系统。"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "按回车键返回主菜单..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    read -r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        *)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "无效选项"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    esac
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    done
                                                           
